primary_emotion = {
    "Angry": ["Let down", "Humiliated", "Bitter", "Mad", "Aggressive", "Frustrated", "Distant", "Critical"],
    "Fearful": ["Scared", "Anxious", "Insecure", "Weak", "Rejected", "Threatened"],
    "Bad": ["Bored", "Busy", "Stressed", "Tired"],
    "Happy": ["Playful", "Content", "Interested", "Proud", "Accepted", "Powerful", "Peaceful", "Trusting", "Optimistic"],
    "Surprised": ["Startled", "Confused", "Amazed", "Excited"],
    "Disgusted": ["Disapproving", "Disappointed", "Awful", "Repelled"],
    "Sad": ["Lonely", "Vulnerable", "Despair", "Guilty", "Depressed", "Hurt"]
  }

secondary_emotion = {
    "Let down": ["Betrayed", "Resentful"],
    "Humiliated": ["Disrespected", "Ridiculed"],
    "Bitter": ["Indignant", "Violated"],
    "Mad": ["Furious", "Jealous"],
    "Aggressive": ["Provoked", "Hostile"],
    "Frustrated": ["Infuriated", "Annoyed"],
    "Distant": ["Withdrawn", "Numb"],
    "Critical": ["Skeptical", "Dismissive"],
    "Scared": ["Helpless", "Frightened"],
    "Anxious": ["Overwhelmed", "Worried"],
    "Insecure": ["Inadequate", "Inferior"],
    "Weak": ["Worthless", "Insignificant"],
    "Rejected": ["Excluded", "Persecuted"],
    "Threatened": ["Nervous", "Exposed"],
    "Bored": ["Indifferent", "Apathetic"],
    "Busy": ["Pressured", "Rushed"],
    "Stressed": ["Overwhelmed", "Out of control"],
    "Tired": ["Sleepy", "Unfocused"],
    "Playful": ["Aroused", "Cheeky"],
    "Content": ["Free", "Joyful"],
    "Interested": ["Curious", "Inquisitive"],
    "Proud": ["Successful", "Confident"],
    "Accepted": ["Respected", "Valued"],
    "Powerful": ["Courageous", "Creative"],
    "Peaceful": ["Loving", "Thankful"],
    "Trusting": ["Sensitive", "Intimate"],
    "Optimistic": ["Hopeful", "Inspired"],
    "Startled": ["Shocked", "Dismayed"],
    "Confused": ["Disillusioned", "Perplexed"],
    "Amazed": ["Astonished", "Awe"],
    "Excited": ["Eager", "Energetic"],
    "Disapproving": ["Judgmental", "Embarrassed"],
    "Disappointed": ["Appalled", "Revolted"],
    "Awful": ["Nauseated", "Detestable"],
    "Repelled": ["Horrified", "Hesitant"],
    "Lonely": ["Isolated", "Abandoned"],
    "Vulnerable": ["Victimized", "Fragile"],
    "Despair": ["Grief", "Powerless"],
    "Guilty": ["Ashamed", "Remorseful"],
    "Depressed": ["Inferior", "Empty"],
    "Hurt": ["Embarrassed", "Disappointed"]
  }

quotes = {'Betrayed': ['Betrayed_Quote_1',
  'Betrayed_Quote_2',
  'Betrayed_Quote_3',
  'Betrayed_Quote_4',
  'Betrayed_Quote_5'],
 'Resentful': ['Resentful_Quote_1',
  'Resentful_Quote_2',
  'Resentful_Quote_3',
  'Resentful_Quote_4',
  'Resentful_Quote_5'],
 'Disrespected': ['Disrespected_Quote_1',
  'Disrespected_Quote_2',
  'Disrespected_Quote_3',
  'Disrespected_Quote_4',
  'Disrespected_Quote_5'],
 'Ridiculed': ['Ridiculed_Quote_1',
  'Ridiculed_Quote_2',
  'Ridiculed_Quote_3',
  'Ridiculed_Quote_4',
  'Ridiculed_Quote_5'],
 'Indignant': ['Indignant_Quote_1',
  'Indignant_Quote_2',
  'Indignant_Quote_3',
  'Indignant_Quote_4',
  'Indignant_Quote_5'],
 'Violated': ['Violated_Quote_1',
  'Violated_Quote_2',
  'Violated_Quote_3',
  'Violated_Quote_4',
  'Violated_Quote_5'],
 'Furious': ['Furious_Quote_1',
  'Furious_Quote_2',
  'Furious_Quote_3',
  'Furious_Quote_4',
  'Furious_Quote_5'],
 'Jealous': ['Jealous_Quote_1',
  'Jealous_Quote_2',
  'Jealous_Quote_3',
  'Jealous_Quote_4',
  'Jealous_Quote_5'],
 'Provoked': ['Provoked_Quote_1',
  'Provoked_Quote_2',
  'Provoked_Quote_3',
  'Provoked_Quote_4',
  'Provoked_Quote_5'],
 'Hostile': ['Hostile_Quote_1',
  'Hostile_Quote_2',
  'Hostile_Quote_3',
  'Hostile_Quote_4',
  'Hostile_Quote_5'],
 'Infuriated': ['Infuriated_Quote_1',
  'Infuriated_Quote_2',
  'Infuriated_Quote_3',
  'Infuriated_Quote_4',
  'Infuriated_Quote_5'],
 'Annoyed': ['Annoyed_Quote_1',
  'Annoyed_Quote_2',
  'Annoyed_Quote_3',
  'Annoyed_Quote_4',
  'Annoyed_Quote_5'],
 'Withdrawn': ['Withdrawn_Quote_1',
  'Withdrawn_Quote_2',
  'Withdrawn_Quote_3',
  'Withdrawn_Quote_4',
  'Withdrawn_Quote_5'],
 'Numb': ['Numb_Quote_1',
  'Numb_Quote_2',
  'Numb_Quote_3',
  'Numb_Quote_4',
  'Numb_Quote_5'],
 'Skeptical': ['Skeptical_Quote_1',
  'Skeptical_Quote_2',
  'Skeptical_Quote_3',
  'Skeptical_Quote_4',
  'Skeptical_Quote_5'],
 'Dismissive': ['Dismissive_Quote_1',
  'Dismissive_Quote_2',
  'Dismissive_Quote_3',
  'Dismissive_Quote_4',
  'Dismissive_Quote_5'],
 'Helpless': ['Helpless_Quote_1',
  'Helpless_Quote_2',
  'Helpless_Quote_3',
  'Helpless_Quote_4',
  'Helpless_Quote_5'],
 'Frightened': ['Frightened_Quote_1',
  'Frightened_Quote_2',
  'Frightened_Quote_3',
  'Frightened_Quote_4',
  'Frightened_Quote_5'],
 'Overwhelmed': ['Overwhelmed_Quote_1',
  'Overwhelmed_Quote_2',
  'Overwhelmed_Quote_3',
  'Overwhelmed_Quote_4',
  'Overwhelmed_Quote_5'],
 'Worried': ['Worried_Quote_1',
  'Worried_Quote_2',
  'Worried_Quote_3',
  'Worried_Quote_4',
  'Worried_Quote_5'],
 'Inadequate': ['Inadequate_Quote_1',
  'Inadequate_Quote_2',
  'Inadequate_Quote_3',
  'Inadequate_Quote_4',
  'Inadequate_Quote_5'],
 'Inferior': ['Inferior_Quote_1',
  'Inferior_Quote_2',
  'Inferior_Quote_3',
  'Inferior_Quote_4',
  'Inferior_Quote_5'],
 'Worthless': ['Worthless_Quote_1',
  'Worthless_Quote_2',
  'Worthless_Quote_3',
  'Worthless_Quote_4',
  'Worthless_Quote_5'],
 'Insignificant': ['Insignificant_Quote_1',
  'Insignificant_Quote_2',
  'Insignificant_Quote_3',
  'Insignificant_Quote_4',
  'Insignificant_Quote_5'],
 'Excluded': ['Excluded_Quote_1',
  'Excluded_Quote_2',
  'Excluded_Quote_3',
  'Excluded_Quote_4',
  'Excluded_Quote_5'],
 'Persecuted': ['Persecuted_Quote_1',
  'Persecuted_Quote_2',
  'Persecuted_Quote_3',
  'Persecuted_Quote_4',
  'Persecuted_Quote_5'],
 'Nervous': ['Nervous_Quote_1',
  'Nervous_Quote_2',
  'Nervous_Quote_3',
  'Nervous_Quote_4',
  'Nervous_Quote_5'],
 'Exposed': ['Exposed_Quote_1',
  'Exposed_Quote_2',
  'Exposed_Quote_3',
  'Exposed_Quote_4',
  'Exposed_Quote_5'],
 'Indifferent': ['Indifferent_Quote_1',
  'Indifferent_Quote_2',
  'Indifferent_Quote_3',
  'Indifferent_Quote_4',
  'Indifferent_Quote_5'],
 'Apathetic': ['Apathetic_Quote_1',
  'Apathetic_Quote_2',
  'Apathetic_Quote_3',
  'Apathetic_Quote_4',
  'Apathetic_Quote_5'],
 'Pressured': ['Pressured_Quote_1',
  'Pressured_Quote_2',
  'Pressured_Quote_3',
  'Pressured_Quote_4',
  'Pressured_Quote_5'],
 'Rushed': ['Rushed_Quote_1',
  'Rushed_Quote_2',
  'Rushed_Quote_3',
  'Rushed_Quote_4',
  'Rushed_Quote_5'],
 'Out of control': ['Out of control_Quote_1',
  'Out of control_Quote_2',
  'Out of control_Quote_3',
  'Out of control_Quote_4',
  'Out of control_Quote_5'],
 'Sleepy': ['Sleepy_Quote_1',
  'Sleepy_Quote_2',
  'Sleepy_Quote_3',
  'Sleepy_Quote_4',
  'Sleepy_Quote_5'],
 'Unfocused': ['Unfocused_Quote_1',
  'Unfocused_Quote_2',
  'Unfocused_Quote_3',
  'Unfocused_Quote_4',
  'Unfocused_Quote_5'],
 'Aroused': ['Aroused_Quote_1',
  'Aroused_Quote_2',
  'Aroused_Quote_3',
  'Aroused_Quote_4',
  'Aroused_Quote_5'],
 'Cheeky': ['Cheeky_Quote_1',
  'Cheeky_Quote_2',
  'Cheeky_Quote_3',
  'Cheeky_Quote_4',
  'Cheeky_Quote_5'],
 'Free': ['Free_Quote_1',
  'Free_Quote_2',
  'Free_Quote_3',
  'Free_Quote_4',
  'Free_Quote_5'],
 'Joyful': ['Joyful_Quote_1',
  'Joyful_Quote_2',
  'Joyful_Quote_3',
  'Joyful_Quote_4',
  'Joyful_Quote_5'],
 'Curious': ['Curious_Quote_1',
  'Curious_Quote_2',
  'Curious_Quote_3',
  'Curious_Quote_4',
  'Curious_Quote_5'],
 'Inquisitive': ['Inquisitive_Quote_1',
  'Inquisitive_Quote_2',
  'Inquisitive_Quote_3',
  'Inquisitive_Quote_4',
  'Inquisitive_Quote_5'],
 'Successful': ['Successful_Quote_1',
  'Successful_Quote_2',
  'Successful_Quote_3',
  'Successful_Quote_4',
  'Successful_Quote_5'],
 'Confident': ['Confident_Quote_1',
  'Confident_Quote_2',
  'Confident_Quote_3',
  'Confident_Quote_4',
  'Confident_Quote_5'],
 'Respected': ['Respected_Quote_1',
  'Respected_Quote_2',
  'Respected_Quote_3',
  'Respected_Quote_4',
  'Respected_Quote_5'],
 'Valued': ['Valued_Quote_1',
  'Valued_Quote_2',
  'Valued_Quote_3',
  'Valued_Quote_4',
  'Valued_Quote_5'],
 'Courageous': ['Courageous_Quote_1',
  'Courageous_Quote_2',
  'Courageous_Quote_3',
  'Courageous_Quote_4',
  'Courageous_Quote_5'],
 'Creative': ['Creative_Quote_1',
  'Creative_Quote_2',
  'Creative_Quote_3',
  'Creative_Quote_4',
  'Creative_Quote_5'],
 'Loving': ['Loving_Quote_1',
  'Loving_Quote_2',
  'Loving_Quote_3',
  'Loving_Quote_4',
  'Loving_Quote_5'],
 'Thankful': ['Thankful_Quote_1',
  'Thankful_Quote_2',
  'Thankful_Quote_3',
  'Thankful_Quote_4',
  'Thankful_Quote_5'],
 'Sensitive': ['Sensitive_Quote_1',
  'Sensitive_Quote_2',
  'Sensitive_Quote_3',
  'Sensitive_Quote_4',
  'Sensitive_Quote_5'],
 'Intimate': ['Intimate_Quote_1',
  'Intimate_Quote_2',
  'Intimate_Quote_3',
  'Intimate_Quote_4',
  'Intimate_Quote_5'],
 'Hopeful': ['Hopeful_Quote_1',
  'Hopeful_Quote_2',
  'Hopeful_Quote_3',
  'Hopeful_Quote_4',
  'Hopeful_Quote_5'],
 'Inspired': ['Inspired_Quote_1',
  'Inspired_Quote_2',
  'Inspired_Quote_3',
  'Inspired_Quote_4',
  'Inspired_Quote_5'],
 'Shocked': ['Shocked_Quote_1',
  'Shocked_Quote_2',
  'Shocked_Quote_3',
  'Shocked_Quote_4',
  'Shocked_Quote_5'],
 'Dismayed': ['Dismayed_Quote_1',
  'Dismayed_Quote_2',
  'Dismayed_Quote_3',
  'Dismayed_Quote_4',
  'Dismayed_Quote_5'],
 'Disillusioned': ['Disillusioned_Quote_1',
  'Disillusioned_Quote_2',
  'Disillusioned_Quote_3',
  'Disillusioned_Quote_4',
  'Disillusioned_Quote_5'],
 'Perplexed': ['Perplexed_Quote_1',
  'Perplexed_Quote_2',
  'Perplexed_Quote_3',
  'Perplexed_Quote_4',
  'Perplexed_Quote_5'],
 'Astonished': ['Astonished_Quote_1',
  'Astonished_Quote_2',
  'Astonished_Quote_3',
  'Astonished_Quote_4',
  'Astonished_Quote_5'],
 'Awe': ['Awe_Quote_1',
  'Awe_Quote_2',
  'Awe_Quote_3',
  'Awe_Quote_4',
  'Awe_Quote_5'],
 'Eager': ['Eager_Quote_1',
  'Eager_Quote_2',
  'Eager_Quote_3',
  'Eager_Quote_4',
  'Eager_Quote_5'],
 'Energetic': ['Energetic_Quote_1',
  'Energetic_Quote_2',
  'Energetic_Quote_3',
  'Energetic_Quote_4',
  'Energetic_Quote_5'],
 'Judgmental': ['Judgmental_Quote_1',
  'Judgmental_Quote_2',
  'Judgmental_Quote_3',
  'Judgmental_Quote_4',
  'Judgmental_Quote_5'],
 'Embarrassed': ['Embarrassed_Quote_1',
  'Embarrassed_Quote_2',
  'Embarrassed_Quote_3',
  'Embarrassed_Quote_4',
  'Embarrassed_Quote_5'],
 'Appalled': ['Appalled_Quote_1',
  'Appalled_Quote_2',
  'Appalled_Quote_3',
  'Appalled_Quote_4',
  'Appalled_Quote_5'],
 'Revolted': ['Revolted_Quote_1',
  'Revolted_Quote_2',
  'Revolted_Quote_3',
  'Revolted_Quote_4',
  'Revolted_Quote_5'],
 'Nauseated': ['Nauseated_Quote_1',
  'Nauseated_Quote_2',
  'Nauseated_Quote_3',
  'Nauseated_Quote_4',
  'Nauseated_Quote_5'],
 'Detestable': ['Detestable_Quote_1',
  'Detestable_Quote_2',
  'Detestable_Quote_3',
  'Detestable_Quote_4',
  'Detestable_Quote_5'],
 'Horrified': ['Horrified_Quote_1',
  'Horrified_Quote_2',
  'Horrified_Quote_3',
  'Horrified_Quote_4',
  'Horrified_Quote_5'],
 'Hesitant': ['Hesitant_Quote_1',
  'Hesitant_Quote_2',
  'Hesitant_Quote_3',
  'Hesitant_Quote_4',
  'Hesitant_Quote_5'],
 'Isolated': ['Isolated_Quote_1',
  'Isolated_Quote_2',
  'Isolated_Quote_3',
  'Isolated_Quote_4',
  'Isolated_Quote_5'],
 'Abandoned': ['Abandoned_Quote_1',
  'Abandoned_Quote_2',
  'Abandoned_Quote_3',
  'Abandoned_Quote_4',
  'Abandoned_Quote_5'],
 'Victimized': ['Victimized_Quote_1',
  'Victimized_Quote_2',
  'Victimized_Quote_3',
  'Victimized_Quote_4',
  'Victimized_Quote_5'],
 'Fragile': ['Fragile_Quote_1',
  'Fragile_Quote_2',
  'Fragile_Quote_3',
  'Fragile_Quote_4',
  'Fragile_Quote_5'],
 'Grief': ['Grief_Quote_1',
  'Grief_Quote_2',
  'Grief_Quote_3',
  'Grief_Quote_4',
  'Grief_Quote_5'],
 'Powerless': ['Powerless_Quote_1',
  'Powerless_Quote_2',
  'Powerless_Quote_3',
  'Powerless_Quote_4',
  'Powerless_Quote_5'],
 'Ashamed': ['Ashamed_Quote_1',
  'Ashamed_Quote_2',
  'Ashamed_Quote_3',
  'Ashamed_Quote_4',
  'Ashamed_Quote_5'],
 'Remorseful': ['Remorseful_Quote_1',
  'Remorseful_Quote_2',
  'Remorseful_Quote_3',
  'Remorseful_Quote_4',
  'Remorseful_Quote_5'],
 'Empty': ['Empty_Quote_1',
  'Empty_Quote_2',
  'Empty_Quote_3',
  'Empty_Quote_4',
  'Empty_Quote_5'],
 'Disappointed': ['Disappointed_Quote_1',
  'Disappointed_Quote_2',
  'Disappointed_Quote_3',
  'Disappointed_Quote_4',
  'Disappointed_Quote_5']}